# Generated by Django 3.1.7 on 2022-02-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220221_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hash',
            field=models.TextField(default=''),
        ),
    ]
