# Generated by Django 3.1.7 on 2022-02-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_file_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='hash',
            new_name='hashCode',
        ),
    ]
