# Generated by Django 3.1.7 on 2022-02-26 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220224_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='uploaded_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
